// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Kwutzke/holepunch/internal/engine (interfaces: DNSManager,SessionManager,IPAllocator,ProxyFactory,TCPProxy)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=internal/engine/mocks/mock_ports.go github.com/Kwutzke/holepunch/internal/engine DNSManager,SessionManager,IPAllocator,ProxyFactory,TCPProxy
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	net "net"
	reflect "reflect"

	dns "github.com/Kwutzke/holepunch/internal/dns"
	engine "github.com/Kwutzke/holepunch/internal/engine"
	session "github.com/Kwutzke/holepunch/internal/session"
	gomock "go.uber.org/mock/gomock"
)

// MockDNSManager is a mock of DNSManager interface.
type MockDNSManager struct {
	ctrl     *gomock.Controller
	recorder *MockDNSManagerMockRecorder
	isgomock struct{}
}

// MockDNSManagerMockRecorder is the mock recorder for MockDNSManager.
type MockDNSManagerMockRecorder struct {
	mock *MockDNSManager
}

// NewMockDNSManager creates a new mock instance.
func NewMockDNSManager(ctrl *gomock.Controller) *MockDNSManager {
	mock := &MockDNSManager{ctrl: ctrl}
	mock.recorder = &MockDNSManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDNSManager) EXPECT() *MockDNSManagerMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockDNSManager) Add(ctx context.Context, entries []dns.Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockDNSManagerMockRecorder) Add(ctx, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockDNSManager)(nil).Add), ctx, entries)
}

// Remove mocks base method.
func (m *MockDNSManager) Remove(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockDNSManagerMockRecorder) Remove(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockDNSManager)(nil).Remove), ctx)
}

// RemoveEntries mocks base method.
func (m *MockDNSManager) RemoveEntries(ctx context.Context, entries []dns.Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveEntries", ctx, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveEntries indicates an expected call of RemoveEntries.
func (mr *MockDNSManagerMockRecorder) RemoveEntries(ctx, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEntries", reflect.TypeOf((*MockDNSManager)(nil).RemoveEntries), ctx, entries)
}

// MockSessionManager is a mock of SessionManager interface.
type MockSessionManager struct {
	ctrl     *gomock.Controller
	recorder *MockSessionManagerMockRecorder
	isgomock struct{}
}

// MockSessionManagerMockRecorder is the mock recorder for MockSessionManager.
type MockSessionManagerMockRecorder struct {
	mock *MockSessionManager
}

// NewMockSessionManager creates a new mock instance.
func NewMockSessionManager(ctrl *gomock.Controller) *MockSessionManager {
	mock := &MockSessionManager{ctrl: ctrl}
	mock.recorder = &MockSessionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionManager) EXPECT() *MockSessionManagerMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockSessionManager) Start(ctx context.Context, params session.StartParams) (session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, params)
	ret0, _ := ret[0].(session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockSessionManagerMockRecorder) Start(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSessionManager)(nil).Start), ctx, params)
}

// MockIPAllocator is a mock of IPAllocator interface.
type MockIPAllocator struct {
	ctrl     *gomock.Controller
	recorder *MockIPAllocatorMockRecorder
	isgomock struct{}
}

// MockIPAllocatorMockRecorder is the mock recorder for MockIPAllocator.
type MockIPAllocatorMockRecorder struct {
	mock *MockIPAllocator
}

// NewMockIPAllocator creates a new mock instance.
func NewMockIPAllocator(ctrl *gomock.Controller) *MockIPAllocator {
	mock := &MockIPAllocator{ctrl: ctrl}
	mock.recorder = &MockIPAllocatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPAllocator) EXPECT() *MockIPAllocatorMockRecorder {
	return m.recorder
}

// Allocate mocks base method.
func (m *MockIPAllocator) Allocate(key string) (net.IP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allocate", key)
	ret0, _ := ret[0].(net.IP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allocate indicates an expected call of Allocate.
func (mr *MockIPAllocatorMockRecorder) Allocate(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allocate", reflect.TypeOf((*MockIPAllocator)(nil).Allocate), key)
}

// Release mocks base method.
func (m *MockIPAllocator) Release(key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release", key)
}

// Release indicates an expected call of Release.
func (mr *MockIPAllocatorMockRecorder) Release(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockIPAllocator)(nil).Release), key)
}

// MockProxyFactory is a mock of ProxyFactory interface.
type MockProxyFactory struct {
	ctrl     *gomock.Controller
	recorder *MockProxyFactoryMockRecorder
	isgomock struct{}
}

// MockProxyFactoryMockRecorder is the mock recorder for MockProxyFactory.
type MockProxyFactoryMockRecorder struct {
	mock *MockProxyFactory
}

// NewMockProxyFactory creates a new mock instance.
func NewMockProxyFactory(ctrl *gomock.Controller) *MockProxyFactory {
	mock := &MockProxyFactory{ctrl: ctrl}
	mock.recorder = &MockProxyFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProxyFactory) EXPECT() *MockProxyFactoryMockRecorder {
	return m.recorder
}

// NewProxy mocks base method.
func (m *MockProxyFactory) NewProxy(ctx context.Context, cfg engine.ProxyConfig) (engine.TCPProxy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewProxy", ctx, cfg)
	ret0, _ := ret[0].(engine.TCPProxy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewProxy indicates an expected call of NewProxy.
func (mr *MockProxyFactoryMockRecorder) NewProxy(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewProxy", reflect.TypeOf((*MockProxyFactory)(nil).NewProxy), ctx, cfg)
}

// MockTCPProxy is a mock of TCPProxy interface.
type MockTCPProxy struct {
	ctrl     *gomock.Controller
	recorder *MockTCPProxyMockRecorder
	isgomock struct{}
}

// MockTCPProxyMockRecorder is the mock recorder for MockTCPProxy.
type MockTCPProxyMockRecorder struct {
	mock *MockTCPProxy
}

// NewMockTCPProxy creates a new mock instance.
func NewMockTCPProxy(ctrl *gomock.Controller) *MockTCPProxy {
	mock := &MockTCPProxy{ctrl: ctrl}
	mock.recorder = &MockTCPProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTCPProxy) EXPECT() *MockTCPProxyMockRecorder {
	return m.recorder
}

// ListenAddr mocks base method.
func (m *MockTCPProxy) ListenAddr() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenAddr")
	ret0, _ := ret[0].(string)
	return ret0
}

// ListenAddr indicates an expected call of ListenAddr.
func (mr *MockTCPProxyMockRecorder) ListenAddr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenAddr", reflect.TypeOf((*MockTCPProxy)(nil).ListenAddr))
}

// Stop mocks base method.
func (m *MockTCPProxy) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockTCPProxyMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockTCPProxy)(nil).Stop))
}
